name: CourierNew
version: 1.3.5
description: A unique mail system
author: Jeremaster101
main: jeremynoesen.couriernew.CourierNew
api-version: 1.14
commands:
  letter:
    description: Create a one-page letter or add pages to an existing letter
    usage: /<command>
  post:
    description: Send a letter to a player(s)
    usage: /<command>
  cnhelp:
    description: CourierNew help command
    usage: /<command>
  shred:
    description: Delete a letter you are holding
    usage: /<command>
  shredall:
    description: Delete all letters in your inventory
    usage: /<command>
  unread:
    description: Retreive unread mail
    usage: /<command>
  cnreload:
    description: Reload the config and messages
    usage: /<command>