# Change delays related to sending mail, the postman, and
# when the postman will appear. All values are in
# minecraft ticks. 20 ticks equals 1 second.
# Radius is in blocks.
join-recieve-delay: 300
send-recieve-delay: 100
resend-delay: 2400
unread-delay: 100
check-before-spawning-postman-radius: 10
remove-postman-ignored-delay: 200
remove-postman-recieved-delay: 20
resend-from-blocked-delay: 100
protected-postman: true
postman-entity-type: VILLAGER
postman-spawn-distance: 3
blocked-gamemodes:
  - GAMEMODE
blocked-worlds:
  - world_name